@startuml
class Shop {
  - ID id
  - string name
  - Prefecture prefecture
  - City city
  - User owner
}
class Prefecture {
  - ID id
  - string name
}
class City {
  - ID id
  - string name
}
class User {
  - ID id
  - string name
}

Shop o-- Prefecture
Shop o-- City
Shop o-- User
@enduml